language: node_js
node_js:
- '4.0'
- '4.1'
- '4.4'
- '5.1'
sudo: false
services:
before_install:
- npm --version
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
notifications:
  email: true
after_failure: cat /home/travis/build/smartbiz/angular2-wordpress/npm-debug.log
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://gitter.im/smartbiz/Angular2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
env:
  global:
  # https://github.com/DefinitelyTyped/tsd#tsdrc
  # Token has no scope (read-only access to public information)
  - TSD_GITHUB_TOKEN=03b1bd86b75abe3e9e2f56c948778e674beb8fd5
